<?php
function sanitize_text_field($v){return trim((string)$v);} function get_current_user_id(){return 42;} function current_time($t){return '2026-09-14 18:40:00';} function wp_unslash($v){return $v;}
function stti_v070_text($v){return sanitize_text_field($v);} function stti_v070_review_status($v){$v=stti_v070_text($v);return in_array($v,['pending','confirmed','rejected'],true)?$v:'pending';} function stti_v070_review_actor($i){$a=(int)($i['reviewed_by']??0);return $a>0?$a:null;} function stti_v070_review_time($i){$v=stti_v070_text($i['reviewed_at']??'');return $v!==''?$v:null;}
function stti_v070_index_by_id($items,$f){$o=[];foreach($items as $i)if(is_array($i)&&!empty($i[$f]))$o[(string)$i[$f]]=$i;return $o;} function stti_v070_stamp_review_transitions($new,$old,$f){$m=stti_v070_index_by_id($old,$f);foreach($new as &$i){$id=(string)($i[$f]??'');$s=stti_v070_review_status($i['review_status']??'pending');$o=$m[$id]??null;$os=is_array($o)?stti_v070_review_status($o['review_status']??'pending'):null;if($s==='pending'){$i['reviewed_by']=null;$i['reviewed_at']=null;}elseif($os===$s&&!empty($o['reviewed_at'])){$i['reviewed_by']=(int)($o['reviewed_by']??0)?:null;$i['reviewed_at']=stti_v070_review_time($o);}else{$i['reviewed_by']=42;$i['reviewed_at']='2026-09-14 18:40:00';}}unset($i);return $new;}
require_once __DIR__.'/../includes/geo-resolver.php';
$n=0;$ok=function($c,$m)use(&$n){if(!$c){fwrite(STDERR,"FAIL: $m\n");exit(1);}echo "PASS: $m\n";$n++;};
$records=[['stop_ref'=>'R1','latitude'=>'35.6892','longitude'=>'51.3890','source_type'=>'source','source_ref'=>'brochure-map','review_status'=>'confirmed'],['stop_ref'=>'R2','latitude'=>32.6546,'longitude'=>51.6680,'source_type'=>'manual_verified','source_ref'=>'review:operator','review_status'=>'confirmed']];
$p=['lifecycle'=>['editorial'=>'needs_review'],'route'=>['stops'=>[['stop_id'=>'R1','city'=>'Tehran'],['stop_id'=>'R2','city'=>'Isfahan']]],'geo'=>['route_stops'=>$records]];
$r=stti_v071_geo_review($p);$ok($r['status']==='ready','confirmed source-backed geo ready');$ok($r['counts']['confirmed']===2,'two confirmed geo rows');
$c=stti_v071_customer_map_config($p,'STT-000001','abc');$ok(count($c['stops'])===2,'renderer gets two canonical points');$ok(!isset($c['geocoder'])&&!isset($c['cacheNamespace']),'renderer config has no geocoder/cache');$ok(isset($c['stops'][0]['lat'])&&isset($c['stops'][0]['lng']),'renderer receives explicit coordinates');
$q=$p;$q['geo']['route_stops'][0]['review_status']='pending';$r=stti_v071_geo_review($q);$ok($r['status']==='pending','pending geo blocks readiness');$c=stti_v071_customer_map_config($q,'X','Y');$ok(count($c['stops'])===1&&count($c['unresolved'])===1,'pending geo excluded from map');
$q=$p;$q['geo']['route_stops'][0]['source_ref']='';$r=stti_v071_geo_review($q);$ok(!$r['ready_for_renderer'],'missing source ref blocks');
$q=$p;$q['geo']['route_stops'][0]['source_type']='unknown';$r=stti_v071_geo_review($q);$ok(!$r['ready_for_renderer'],'unknown source type blocks');
$q=$p;$q['geo']['route_stops'][0]['latitude']=null;$q['geo']['route_stops'][0]['review_status']='confirmed';$r=stti_v071_geo_review($q);$ok((bool)array_filter($r['errors'],fn($x)=>str_contains($x,'cannot be confirmed')),'unresolved cannot be confirmed');
$q=$p;$q['geo']['route_stops'][0]['stop_ref']='RX';$r=stti_v071_geo_review($q);$ok((bool)array_filter($r['errors'],fn($x)=>str_contains($x,'unknown stop')),'unknown stop ref errors');
$q=$p;$q['geo']['route_stops'][]=$q['geo']['route_stops'][0];$r=stti_v071_geo_review($q);$ok((bool)array_filter($r['errors'],fn($x)=>str_contains($x,'Duplicate geo')),'duplicate geo refs error');
$q=$p;$q['route']['stops'][0]['stop_id']='';$r=stti_v071_geo_review($q);$ok((bool)array_filter($r['blockers'],fn($x)=>str_contains($x,'no canonical stop_id')),'missing stop id blocks canonical geo');
$q=$p;array_pop($q['geo']['route_stops']);$r=stti_v071_geo_review($q);$ok((bool)array_filter($r['blockers'],fn($x)=>str_contains($x,'has no geo record')),'missing geo row blocks');
$q=$p;$q['lifecycle']['editorial']='approved';$q['geo']['route_stops'][0]['review_status']='pending';$r=stti_v071_geo_review($q);$ok((bool)array_filter($r['errors'],fn($x)=>str_contains($x,'Editorial approval is blocked')),'approved cannot bypass geo gate');
$norm=stti_v071_normalize_geo_records([['stop_ref'=>'R1','latitude'=>91,'longitude'=>10,'review_status'=>'pending']]);$ok($norm[0]['state']==='unresolved'&&$norm[0]['latitude']===null,'out-of-range coordinate normalizes unresolved');
$norm=stti_v071_normalize_geo_records([['stop_ref'=>'R1','latitude'=>'35,5','longitude'=>'51,2']]);$ok($norm[0]['state']==='resolved'&&abs($norm[0]['latitude']-35.5)<0.0001,'comma decimals normalize');
$old=[['stop_ref'=>'R1','state'=>'unresolved','latitude'=>null,'longitude'=>null,'source_type'=>'unknown','source_ref'=>'','review_status'=>'pending','reviewed_by'=>999,'reviewed_at'=>'forged']];$base=['route'=>['stops'=>[['stop_id'=>'R1']]],'lifecycle'=>['editorial'=>'needs_review']];$e=stti_v071_enrich_payload($base,['geo'=>['route_stops'=>$old]],json_encode([['stop_ref'=>'R1','latitude'=>35,'longitude'=>51,'source_type'=>'source','source_ref'=>'src','review_status'=>'confirmed','reviewed_by'=>999,'reviewed_at'=>'forged']]));$g=$e['geo']['route_stops'][0];$ok($g['reviewed_by']===42,'client reviewer replaced by server');$ok($g['reviewed_at']==='2026-09-14 18:40:00','server timestamp owns geo review');
$old=$e['geo']['route_stops'];$e2=stti_v071_enrich_payload($base,['geo'=>['route_stops'=>$old]],json_encode($old));$ok($e2['geo']['route_stops'][0]['reviewed_by']===42,'unchanged confirmed geo preserves audit');
$pending=$old;$pending[0]['review_status']='pending';$e3=stti_v071_enrich_payload($base,['geo'=>['route_stops'=>$old]],json_encode($pending));$ok($e3['geo']['route_stops'][0]['reviewed_by']===null&&$e3['geo']['route_stops'][0]['reviewed_at']===null,'pending clears audit metadata');
$q=$p;$q['geo']['route_stops'][0]['review_status']='rejected';$c=stti_v071_customer_map_config($q,'X','Y');$ok(count($c['stops'])===1,'rejected geo never reaches renderer');
$ok($n===22,'expected assertion count');echo "STTI v0.7.1 Canonical Geo Resolver contract: PASS\n";
