<?php
function get_current_user_id(){return 42;} function current_time($type){return '2026-09-14 16:00:00';}
require_once __DIR__.'/../includes/review-relations.php';
$n=0;$ok=function($c,$m)use(&$n){if(!$c){fwrite(STDERR,"FAIL: $m\n");exit(1);}echo "PASS: $m\n";$n++;};
$resolver=fn($id)=>preg_match('/^STH-\d{6}$/',$id)?['status'=>'resolved','hotel_id'=>$id,'post_id'=>7]:['status'=>'invalid','hotel_id'=>$id];
$payload=['lifecycle'=>['editorial'=>'needs_review'],'route'=>['stops'=>[['stop_id'=>'R1'],['stop_id'=>'R2']],'variants'=>[['variant_id'=>'V1','role'=>'primary','stop_refs'=>['R1','R2'],'hotel_relation_refs'=>['H1'],'transport_segment_refs'=>['T1'],'review_status'=>'confirmed']]],'stays'=>['hotels'=>[['relation_id'=>'H1','mode'=>'hotel_intelligence','hotel_stable_id'=>'STH-000001','option_group_id'=>'HG1','selection_status'=>'selected','review_status'=>'confirmed']]],'transport'=>['segments'=>[['segment_id'=>'T1','from_stop_ref'=>'R1','to_stop_ref'=>'R2','route_variant_ref'=>'V1','review_status'=>'confirmed']]]];
$r=stti_v070_relation_review($payload,$resolver);$ok($r['status']==='ready','full relation graph ready');$ok($r['ready_for_editorial_approval'],'approval ready');$ok($r['counts']['confirmed']===3,'three confirmed relations');
$link=stti_v070_hotel_link_state('bad');$ok(array_keys($link)===['status','hotel_id'],'hotel resolver returns identity state only');
$p=$payload;$p['route']['variants'][0]['review_status']='pending';$r=stti_v070_relation_review($p,$resolver);$ok($r['status']==='pending','pending stays pending');$ok(!$r['ready_for_editorial_approval'],'pending blocks readiness');$p['lifecycle']['editorial']='approved';$r=stti_v070_relation_review($p,$resolver);$ok((bool)array_filter($r['errors'],fn($x)=>str_contains($x,'approval is blocked')),'approval cannot bypass review');
$p=$payload;$p['route']['variants'][0]['stop_refs'][]='RX';$r=stti_v070_relation_review($p,$resolver);$ok((bool)array_filter($r['errors'],fn($x)=>str_contains($x,'unknown stop')),'unknown stop ref errors');
$ok(stti_v070_hotel_link_state('sth-000123')['hotel_id']==='STH-000123','hotel stable ID uppercases');$ok(stti_v070_hotel_link_state('STH-123')['status']==='invalid','hotel stable ID requires six digits');
$p=$payload;$p['stays']['hotels'][0]=['relation_id'=>'H1','mode'=>'unresolved','unresolved_name'=>'Source Hotel','review_status'=>'confirmed'];$r=stti_v070_relation_review($p,$resolver);$ok($r['normalized']['hotel_relations'][0]['unresolved_name']==='Source Hotel','unresolved source hotel preserved');$ok(!$r['ready_for_editorial_approval'],'unresolved hotel blocks approval');
$legacy=['lifecycle'=>['editorial'=>'needs_review'],'route'=>['stops'=>[['label'=>'Tehran']]],'stays'=>['hotels'=>[]],'transport'=>['segments'=>[]]];$r=stti_v070_relation_review($legacy,$resolver);$ok(!$r['errors'],'legacy no-relations candidate remains compatible');$ok(stti_v070_review_status(null)==='pending','legacy review defaults pending');$ok(stti_v070_hotel_selection_status(null)==='unknown','legacy hotel selection defaults unknown');
$p=$payload;$p['stays']['hotels'][]=['relation_id'=>'H2','mode'=>'hotel_intelligence','hotel_stable_id'=>'STH-000002','option_group_id'=>'HG1','selection_status'=>'selected','review_status'=>'confirmed'];$r=stti_v070_relation_review($p,$resolver);$ok((bool)array_filter($r['errors'],fn($x)=>str_contains($x,'more than one selected')),'duplicate selected option group errors');
$p=$payload;$p['route']['variants'][]=['variant_id'=>'V2','role'=>'primary','review_status'=>'confirmed'];$r=stti_v070_relation_review($p,$resolver);$ok((bool)array_filter($r['errors'],fn($x)=>str_contains($x,'More than one active')),'multiple primary variants error');
$p=$payload;$p['stays']['hotels'][]=['relation_id'=>'H2','mode'=>'unresolved','unresolved_name'=>'Rejected','review_status'=>'rejected'];$r=stti_v070_relation_review($p,$resolver);$ok($r['ready_for_editorial_approval'],'unreferenced rejected evidence does not block');
$r=stti_v070_relation_review($legacy,$resolver);$ok(!$r['errors'],'legacy stops need no IDs until referenced');
$old=[['variant_id'=>'V1','review_status'=>'pending','reviewed_by'=>999,'reviewed_at'=>'old']];$new=[['variant_id'=>'V1','review_status'=>'confirmed','reviewed_by'=>999,'reviewed_at'=>'forged']];$s=stti_v070_stamp_review_transitions(stti_v070_normalize_route_variants($new),stti_v070_normalize_route_variants($old),'variant_id');$ok($s[0]['reviewed_by']===42,'client reviewer replaced by server');$ok($s[0]['reviewed_at']==='2026-09-14 16:00:00','server review timestamp set');
$old=$s;$new=$s;$new[0]['reviewed_by']=999;$new[0]['reviewed_at']='forged';$s2=stti_v070_stamp_review_transitions($new,$old,'variant_id');$ok($s2[0]['reviewed_by']===42&&$s2[0]['reviewed_at']==='2026-09-14 16:00:00','unchanged status preserves server audit');
$new=$s;$new[0]['review_status']='pending';$s3=stti_v070_stamp_review_transitions($new,$s,'variant_id');$ok($s3[0]['reviewed_by']===null&&$s3[0]['reviewed_at']===null,'pending clears review audit');
$ok($n===23,'expected assertion count');echo "STTI v0.7.0 Review Relations contract: PASS\n";
