<?php
if(!defined('ABSPATH')){exit(1);} 
$ok=static function($c,$m){if(!$c)throw new RuntimeException($m);WP_CLI::log('PASS: '.$m);};
wp_set_current_user(1);global $wpdb;$t=stti_tables();$snapshot=static function()use($wpdb,$t){return array((int)$wpdb->get_var("SELECT COUNT(*) FROM {$t['tours']}"),(int)$wpdb->get_var("SELECT COUNT(*) FROM {$t['audit']}"),(int)get_option('stti_next_sequence',0));};$before=$snapshot();
if(!post_type_exists('sthi_hotel'))register_post_type('sthi_hotel',array('public'=>false,'supports'=>array('title')));
$hotel=wp_insert_post(array('post_type'=>'sthi_hotel','post_status'=>'private','post_title'=>'Renderer Hotel'));$ok(!is_wp_error($hotel)&&$hotel>0,'Hotel fixture created');update_post_meta($hotel,'_sthi_hotel_id','STH-999997');update_post_meta($hotel,'_sthi_display_name_tr','Renderer Canonical Hotel');update_post_meta($hotel,'_sthi_city','İstanbul');
$p=array('route'=>array('stops'=>array(array('stop_id'=>'R1','city'=>'İstanbul'),array('stop_id'=>'R2','city'=>'Bursa'),array('stop_id'=>'R3','city'=>'İzmir')),'variants'=>array(array('variant_id'=>'V1','role'=>'primary','stop_refs'=>array('R1','R2'),'hotel_relation_refs'=>array('H1','H2'),'transport_segment_refs'=>array('T1'),'review_status'=>'confirmed'),array('variant_id'=>'V2','role'=>'alternative','stop_refs'=>array('R2','R3'),'review_status'=>'confirmed'))),'stays'=>array('hotels'=>array(array('relation_id'=>'H1','mode'=>'hotel_intelligence','hotel_stable_id'=>'STH-999997','selection_status'=>'selected','review_status'=>'confirmed'),array('relation_id'=>'H2','mode'=>'unresolved','unresolved_name'=>'Pending','selection_status'=>'alternative','review_status'=>'pending'))),'transport'=>array('segments'=>array(array('segment_id'=>'T1','type'=>'bus','from_stop_ref'=>'R1','to_stop_ref'=>'R2','route_variant_ref'=>'V1','review_status'=>'confirmed'))),'geo'=>array('route_stops'=>array(array('stop_ref'=>'R1','latitude'=>41,'longitude'=>29,'source_type'=>'manual_verified','source_ref'=>'runtime','review_status'=>'confirmed'),array('stop_ref'=>'R2','latitude'=>40,'longitude'=>29,'source_type'=>'manual_verified','source_ref'=>'runtime','review_status'=>'confirmed'))),'lifecycle'=>array('editorial'=>'needs_review'));
$hash=hash('sha256',wp_json_encode($p));$m=stti_v080_renderer_model($p,'STT-999997','x');
$ok(($m['contract']??'')==='STTI-CUSTOMER-RENDERER-1.0.0','v0.8 renderer contract loaded');$ok(($m['variant_state']['active']['variant_id']??'')==='V1','confirmed primary drives renderer');$ok(count($m['route_stops'])===2,'active variant scope preserved');$ok(count($m['hotels'])===1&&($m['hotels'][0]['name']??'')==='Renderer Canonical Hotel','pending hotel excluded and Hotel facts live-read');$ok(count($m['transport'])===1,'confirmed transport rendered');$ok(count($m['map']['stops'])===2&&!isset($m['map']['geocoder'])&&!isset($m['map']['cacheNamespace']),'canonical map has no geocoder/cache authority');$ok($m['public']===false&&$m['indexable']===false&&$m['writes']===0,'renderer remains private and no-write');$q=$p;$q['route']['variants'][0]['role']='alternative';$n=stti_v080_renderer_model($q);$ok(($n['variant_state']['mode']??'')==='no_primary_selected'&&count($n['route_stops'])===0,'renderer never guesses primary route');$ok(hash('sha256',wp_json_encode($p))===$hash&&$snapshot()===$before,'renderer analysis does not mutate payload or canonical tables');wp_delete_post($hotel,true);WP_CLI::log('STTI v0.8.0 Customer Renderer runtime: PASS');
