<?php
if (!defined('ABSPATH')) { fwrite(STDERR, "WordPress bootstrap required\n"); exit(1); }
function stti_v071_runtime_ok($condition,$message){if(!$condition){fwrite(STDERR,"FAIL: {$message}\n");exit(1);}echo "PASS: {$message}\n";}
stti_v071_runtime_ok(defined('STTI_VERSION') && STTI_VERSION==='0.7.1','plugin runtime is STTI v0.7.1');
stti_v071_runtime_ok(function_exists('stti_v071_geo_review'),'canonical geo resolver is loaded');
stti_v071_runtime_ok(function_exists('stti_v071_customer_map_config'),'canonical customer map config is loaded');
wp_set_current_user(1);
$payload=array('route'=>array('stops'=>array(array('stop_id'=>'R1','city'=>'Istanbul'),array('stop_id'=>'R2','city'=>'Cairo'))),'geo'=>array('contract'=>'STTI-GEO-1.0.0','route_stops'=>array(array('stop_ref'=>'R1','latitude'=>41.0082,'longitude'=>28.9784,'source_type'=>'source','source_ref'=>'runtime-fixture-1','review_status'=>'confirmed'),array('stop_ref'=>'R2','latitude'=>30.0444,'longitude'=>31.2357,'source_type'=>'external_reference','source_ref'=>'runtime-fixture-2','review_status'=>'confirmed'))),'lifecycle'=>array('editorial'=>'approved'),'publication'=>array('public_route'=>false,'indexable'=>false,'sitemap'=>false,'schema'=>false,'homepage_adapter'=>false));
$r=stti_v071_geo_review($payload);stti_v071_runtime_ok(($r['status']??'')==='ready'&&($r['ready_for_renderer']??false)===true,'source-backed confirmed geo passes renderer gate');
$c=stti_v071_customer_map_config($payload,'STT-999999','runtime-checksum');stti_v071_runtime_ok(count($c['stops']??[])===2,'customer map receives two canonical points');stti_v071_runtime_ok(!isset($c['geocoder'])&&!isset($c['cacheNamespace'])&&!isset($c['geocodeDelayMs']),'customer map config contains no browser geocoder/cache authority');
$pending=$payload;$pending['lifecycle']['editorial']='needs_review';$pending['geo']['route_stops'][0]['review_status']='pending';$r=stti_v071_geo_review($pending);stti_v071_runtime_ok(($r['status']??'')==='pending','pending geo remains pending');$c=stti_v071_customer_map_config($pending,'STT-999999','x');stti_v071_runtime_ok(count($c['stops']??[])===1&&count($c['unresolved']??[])===1,'pending geo is excluded from renderer points');
$rejected=$payload;$rejected['lifecycle']['editorial']='needs_review';$rejected['geo']['route_stops'][0]['review_status']='rejected';$r=stti_v071_geo_review($rejected);stti_v071_runtime_ok(($r['ready_for_renderer']??true)===false&&(bool)array_filter($r['blockers'],fn($e)=>str_contains($e,'was rejected')),'rejected geo remains a blocker until a confirmed replacement exists');
$missing=$payload;$missing['lifecycle']['editorial']='needs_review';$missing['geo']['route_stops'][0]['source_ref']='';$r=stti_v071_geo_review($missing);stti_v071_runtime_ok(($r['ready_for_renderer']??true)===false,'coordinates without source reference fail closed');
$noid=$payload;$noid['lifecycle']['editorial']='needs_review';$noid['route']['stops'][0]['stop_id']='';$r=stti_v071_geo_review($noid);stti_v071_runtime_ok((bool)array_filter($r['blockers'],fn($e)=>str_contains($e,'no canonical stop_id')),'missing canonical stop identity blocks geo readiness');
$approved=$pending;$approved['lifecycle']['editorial']='approved';$r=stti_v071_geo_review($approved);stti_v071_runtime_ok((bool)array_filter($r['errors'],fn($e)=>str_contains($e,'Editorial approval is blocked')),'editorial approval cannot bypass geo review');
global $wpdb;$tables=stti_tables();$before=array((int)$wpdb->get_var("SELECT COUNT(*) FROM {$tables['tours']}"),(int)$wpdb->get_var("SELECT COUNT(*) FROM {$tables['audit']}"),get_option('stti_next_sequence',null));stti_v071_geo_review($payload);stti_v071_customer_map_config($payload,'STT-999999','x');$after=array((int)$wpdb->get_var("SELECT COUNT(*) FROM {$tables['tours']}"),(int)$wpdb->get_var("SELECT COUNT(*) FROM {$tables['audit']}"),get_option('stti_next_sequence',null));stti_v071_runtime_ok($before===$after,'geo analysis and renderer config perform NO WRITE');
foreach(array('public_route','indexable','sitemap','schema','homepage_adapter') as $lock)stti_v071_runtime_ok(($payload['publication'][$lock]??null)===false,"Tour publication lock {$lock} remains OFF");
echo "STTI v0.7.1 Canonical Geo Resolver WordPress runtime: PASS\n";
